/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.estacionei.api;

import io.swagger.annotations.*;

import org.estacionei.model.Cliente;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.estacionei.codegen.languages.SpringCodegen", date = "2019-09-20T20:35:29.312-03:00[America/Sao_Paulo]")

@Validated
@Api(value = "cliente", description = "the cliente API")
public interface ClienteApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "cadastra um novo cliente", nickname = "clientePost", notes = "cadastra um novo cliente", tags={ "clientes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "criado com sucesso"),
        @ApiResponse(code = 400, message = "requisição invalida") })
    @RequestMapping(value = "/cliente",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Void> clientePost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Cliente cliente) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
