/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.estacionei.api;

import io.swagger.annotations.*;

import org.estacionei.model.Vaga;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.estacionei.codegen.languages.SpringCodegen", date = "2019-09-20T20:35:29.312-03:00[America/Sao_Paulo]")

@Validated
@Api(value = "estacionametos", description = "the estacionametos API")
public interface EstacionametosApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "atualiza status de uma vaga", nickname = "estacionametosIdEstacionamentoVagasIdVagaPatch", notes = "", tags={ "estacionamentos", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "accepted"),
        @ApiResponse(code = 404, message = "id não encontrado"),
        @ApiResponse(code = 400, message = "bad request") })
    @RequestMapping(value = "/estacionametos/{id_estacionamento}/vagas/{id_vaga}",
        consumes = { "application/json" },
        method = RequestMethod.PATCH)
    default ResponseEntity<Void> estacionametosIdEstacionamentoVagasIdVagaPatch(@ApiParam(value = "",required=true) @PathVariable("id_estacionamento") String idEstacionamento,@ApiParam(value = "",required=true) @PathVariable("id_vaga") String idVaga,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Vaga vaga) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
