/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.estacionei.api;

import io.swagger.annotations.*;

import org.estacionei.model.Recibo;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.estacionei.codegen.languages.SpringCodegen", date = "2019-09-20T20:35:29.312-03:00[America/Sao_Paulo]")

@Validated
@Api(value = "recibos", description = "the recibos API")
public interface RecibosApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "busca um recibo", nickname = "recibosIdReciboGet", notes = "consulta um determinado recibo", response = Recibo.class, tags={ "recibos", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Recibo.class),
        @ApiResponse(code = 404, message = "veiculo não encontrado") })
    @RequestMapping(value = "/recibos/{id_recibo}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Recibo> recibosIdReciboGet(@ApiParam(value = "",required=true) @PathVariable("id_recibo") String idRecibo) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"id_estacionamento\" : \"id_estacionamento\",  \"id\" : \"id\"}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "cria um novo recibo", nickname = "recibosPost", notes = "cria um novo recibo apos um pagamento", tags={ "recibos", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "criado com sucesso"),
        @ApiResponse(code = 400, message = "requisição invalida") })
    @RequestMapping(value = "/recibos",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Void> recibosPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Recibo recibo) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
